// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"mongodb-example/src/infrastructure/db/mongo"
	"mongodb-example/src/interfaces/mongo/repository"
	"mongodb-example/src/usecases"
)

// Injectors from wire.go:

func InitializeUserService() (*usecases.UserService, error) {
	config := mongo.DefaultConfig()
	database, err := mongo.NewDbConnection(config)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewMongoUserRepository(database)
	validator := usecases.NewValidator()
	userService := usecases.NewUserService(userRepository, validator)
	return userService, nil
}
