// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package api

import (
	"mongodb-example/src/infrastructure"
	"mongodb-example/src/infrastructure/db/mongo"
	"mongodb-example/src/interfaces/mongo/repository"
	"mongodb-example/src/usecases"
	"net/http/httptest"
)

// Injectors from wire.go:

func InitTestServer() *httptest.Server {
	logger := infrastructure.NewStdLogger()
	config := mongo.TestConfig()
	database := mongo.MustNewDbConnection(config)
	userRepository := repository.NewMongoUserRepository(database)
	validator := usecases.NewValidator()
	userService := usecases.NewUserService(userRepository, validator)
	handler := New(logger, userService)
	server := httptest.NewServer(handler)
	return server
}
