// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"mongodb-example/src/infrastructure"
	"mongodb-example/src/infrastructure/db/mongo"
	"mongodb-example/src/interfaces/api"
	"mongodb-example/src/interfaces/mongo/repository"
	"mongodb-example/src/usecases"
	"net/http"
)

// Injectors from wire.go:

func Init() (http.Handler, error) {
	logger := infrastructure.NewStdLogger()
	config := mongo.DefaultConfig()
	database, err := mongo.NewDbConnection(config)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewMongoUserRepository(database)
	validator := usecases.NewValidator()
	iUserService := usecases.NewUserService(userRepository, validator)
	handler := api.New(logger, iUserService)
	return handler, nil
}
